title: Recipe for Spaghetti and Meatballs
theme: jekyll-theme-minimal
description: A simple recipe to impress your loved ones with.
accent_image: /assets/downloads/spaghetti.jpghttps://guides.github.com/features/pages/